apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: exporter
        image: prom/mysqld-exporter
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-secret
              key: DATA_SOURCE_NAME
        ports:
        - containerPort: 9104

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  labels:
    app: mysql-exporter
spec:
  ports:
  - port: 9104
    targetPort: 9104
  selector:
    app: mysql-exporter