apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: {{ .Values.wordpress.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wordpress